### ISSUE TITLE
Conflict with recent change in phergie-irc-bot-react

### ISSUE THREAD

**Issue by nfauchelle** [WyriHaximus/PhergieHttp#10]
Hello,

With a recent change to the main bot there is now a conflict with this plugin.

The change in the other repo is here and is merged to master. elazar has said he will be tagging this off soon.
https://github.com/phergie/phergie-irc-bot-react/commit/b5e4f79b00f277c797bd37474ad1c006bf716f73

This causes a conflict because this plugin already has a $client and setClient functions/variables which store the HttpClient.

I've gone through and changed $client to $httpClient; and setClient to setHttpClient and seems to be working this far. The tests would need to be updated, but would this impact anything else? I can send a pull request if you'd be happy with that change.

**Comment by WyriHaximus** [comment]
I'm happy with the change, please send a pull request my way :+1: . Since this would be a BC break I'de have to tag a new major version anyway so users of this plugin will now something changed.

**Comment by nfauchelle** [comment]
Done.
Also I noticed when I cloned this repo and ran phpunit I get the error
PHP Fatal error:  Call to undefined method WyriHaximus\Phergie\Plugin\Http\Plugin::setClient() in /*snip*/PhergieHttp/tests/PluginTest.php on line 80

If I open phpunit.xml and add 
    bootstrap="./vendor/autoload.php"
after 
    syntaxCheck="true"
and then it works fine.

I notice other repos don't have that bootstrap thing, so... do you specify it on the command line eg
    phpunit --bootstrap vendor/autoload.php
?

**Comment by WyriHaximus** [comment]
Personally running all tests via `./vendor/bin/phpunit` so the autoloader is included there. Should update documentation on that, and port the [`Makefile`](https://github.com/WyriHaximus/ReactGuzzleRing/blob/master/Makefile) I have in other projects for this to make it as easy as possible for contributors. Thanks for the heads up :+1: .

**Comment by nfauchelle** [comment]
So it does!
Thats for that.
